### PR TITLE
add wangedtior , fix yanquan display bug

### LINKED ISSUE #73: 数据库里有盐圈，但是主页未抓取
这是后端数据库截图

截屏2021-12-28 上午11 41 07

这是主页盐圈截图

截屏2021-12-28 上午11 35 52

### PR DESCRIPTION
**Pull request by hotpot-fish**

### CODE REVIEW

File: src/Source/Components/WangEditor/Toolbar.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
+/**
+ * @description toolbar react component
+ * @author wangfupeng
+ */
```
Comment (DDDDDDDOU) [inline src/Source/Components/WangEditor/Toolbar.js:4]: romove this annotation

File: src/Source/Containers/Forum/ForumBoard.js [hunk 2]
```diff
@@ -41,8 +41,7 @@ export default class ForumBoard extends React.Component {
         this.setState({
             forums: nextProps.Forums,
             paperID: nextProps.PaperID,
-        });
-
+        }, ()=> console.log(this.state.forums));
```
Comment (DDDDDDDOU) [inline src/Source/Containers/Forum/ForumBoard.js:44]: remove this callback function later

File: src/Source/Model/Net/NetService/PostService.js [hunk 3]
```diff
@@ -20,9 +20,9 @@ export  function GetPostByForumID(tid,callback){
 
 }
 
-export function PostPostToForumID(data,callback){
-    let URL=url+`post/`
-    axios.post(URL,data,config).then((res)=>{
+export function PostToForum(data,callback){
+    let URL=url+`forum/addNewPostToForum`
+    axios.post(URL,data,option).then((res)=>{
         callback(res.data)
```
Comment (DDDDDDDOU) [inline src/Source/Model/Net/NetService/PostService.js:26]: use responceDispatcher instead of calling callback() directly

File: src/Source/Model/Net/NetService/ProfileService.js [hunk 4]
```diff
@@ -18,11 +18,11 @@ export function GetProfileList(callback) {
...
 
-export function SetProfileByID(id,data,callback){
-    let URL= `${url}users/userprofile/${id}/`
-    axios.patch(URL,data).then(
+export function SetProfile(data,callback){
+    let URL= `${url}user/setProfile`
+    axios.post(URL,data,option).then(
         (res)=>{
-            callback(res.data)
+            callback(res)
```
Comment (DDDDDDDOU) [inline src/Source/Model/Net/NetService/ProfileService.js:25]: use responceDispatcher instead of calling callback() directly

**Review by DDDDDDDOU — APPROVED** [review]

**Review by DDDDDDDOU — COMMENTED** [review]
resolve all comments before merging
